// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXnOddaRNkVmgiFmpS3815aA8CFpIr0aU',
    appId: '1:11587005773:web:906d3841930c99181fdb04',
    messagingSenderId: '11587005773',
    projectId: 'contas-trabalhistas',
    authDomain: 'contas-trabalhistas.firebaseapp.com',
    databaseURL: 'https://contas-trabalhistas.firebaseio.com',
    storageBucket: 'contas-trabalhistas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXfbuuve_uraciy7I2inf3SQ4Nnc3JEtw',
    appId: '1:11587005773:android:7c487d735d7cfa761fdb04',
    messagingSenderId: '11587005773',
    projectId: 'contas-trabalhistas',
    databaseURL: 'https://contas-trabalhistas.firebaseio.com',
    storageBucket: 'contas-trabalhistas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRzEmQt_UGI0VtWCQB05jsHm9iWNTOXIs',
    appId: '1:11587005773:ios:8a2951165a81dd7d1fdb04',
    messagingSenderId: '11587005773',
    projectId: 'contas-trabalhistas',
    databaseURL: 'https://contas-trabalhistas.firebaseio.com',
    storageBucket: 'contas-trabalhistas.appspot.com',
    androidClientId: '11587005773-4rdejvm8ohkef2td0per6gs20s5eqifq.apps.googleusercontent.com',
    iosClientId: '11587005773-8ros9mtki04v8epkj55u6efbvhvr278t.apps.googleusercontent.com',
    iosBundleId: 'br.cap.sistemas.contastrabalhistas.contastrabalhistas',
  );
}
